#!/bin/sh
# Pre-commit hook for running the Linux coding style checker
# Available at:
#  https://github.com/torvalds/linux/blob/master/scripts/checkpatch.pl
#  https://github.com/torvalds/linux/blob/master/scripts/spelling.txt

CHECKPATCH=~/local/bin/checkpatch.pl

git diff --cached HEAD | $CHECKPATCH --no-tree --no-signoff --summary-file -q --ignore FILE_PATH_CHANGES -

if [ $? != 0 ]; then
    echo "Coding style checked failed.  Please fix warnings and errors and try commiting again."
    exit -1
fi

exit 0
